### ISSUE TITLE
Comments?

### ISSUE THREAD

**Issue by xmo-odoo** [PiotrDabkowski/pyjsparser#14]
The parser seems to ignore/lose comments, I expect the reason is the same as #11 (wasn't necessary) but just in case, any plans to add them?

**Comment by PiotrDabkowski** [comment]
Sorry, I don't add new features to the parser. Pull requests are welcome. 

Alternatively, you can use [my Js2Py translated esprima.js](https://github.com/PiotrDabkowski/Js2Py/blob/master/examples/pyesprima.py). It supports everything, including JavaScript 6 and comments, but unfortunately, it's about 10 times slower than pyjsparser.

**Comment by xmo-odoo** [comment]
> Alternatively, you can use my Js2Py translated esprima.js. It supports everything, including JavaScript 6 and comments, but unfortunately, it's about 10 times slower than pyjsparser.

Yeah sadly it also blows up the stack on the source files I'm feeding it.

Let's say I add some basic comments support to pyjsparser, how much do you care about matching esprima's structure & semantics?

**Comment by PiotrDabkowski** [comment]
Hmm, as long as the current functionality is kept intact, you can add the comments to the current structure any way you like.
