### ISSUE TITLE
Python 3 support is absent

### ISSUE THREAD

**Issue by zxwild** [PiotrDabkowski/pyjsparser#2]
I've forked it and replaced
- iteritems() --> items()
- unichr() --> chr()
- xrange() --> range()
- print '' --> print('') etc..

And fixed some imports, but it's not tested to fit a python2, so I didn't make a pull request.

**Comment by PiotrDabkowski** [comment]
Can you make it work for bothon 2 and 3? Otherwise we can have 2 files - 1 for python 2 and another one for py3.
