### ISSUE TITLE
pyjsparser.pyjsparserdata.JsSyntaxError: Line 1: ArrowFunction is not supported by ECMA 5.1.

### ISSUE THREAD

**Issue by evandrix** [PiotrDabkowski/pyjsparser#31]
e.g. https://sleighworkshopdoor.elfu.org/client.js/e765b964-c1a0-452d-a230-06bd423932da

**Comment by PiotrDabkowski** [comment]
Well, the error says it all: ArrowFunction is not supported by ECMA 5.1. See readme.
