### ISSUE TITLE
no parameter to parseParams()

### ISSUE THREAD

**Issue by mounty1** [PiotrDabkowski/pyjsparser#5]
pyjsparser line 1163 has a call to method parseParams() which does not supply an argument for formal firstRestricted.
In a statically-analysable language, this would not even have been compilable ...

**Comment by petri** [comment]
The bug is now in a different place at the current master: https://github.com/PiotrDabkowski/pyjsparser/blob/master/pyjsparser/parser.py#L1277

**Comment by PiotrDabkowski** [comment]
Thanks, fixed.
