### ISSUE TITLE
improper parsing of truth values

### ISSUE THREAD

**Issue by mounty1** [PiotrDabkowski/pyjsparser#6]
pyjsparser.py line 262 has "elif (i == 'true' or d == 'false'):".  The LHS of the first comparison should be d, not i, which isn't defined in the current scope.

Even with that fixed, the output AST encodes the truth values as Literals.  To output identifiers, I simply commented-out ll 262--263.

**Comment by PiotrDabkowski** [comment]
Wow that was a tricky one, thanks. Fixed
