### ISSUE TITLE
Does not parse single line or multiline comments

### ISSUE THREAD

**Issue by ajinabraham** [PiotrDabkowski/pyjsparser#8]
Is there any way I can parse JavaScript Comments, like below ?

```
//alert(0);
/*
prompt("do you?");
Some comments
*/

**Comment by PiotrDabkowski** [comment]
This is unfortunately not implemented in pyjsparser. 

You can use  [my automatic translation of esprima](https://github.com/PiotrDabkowski/Js2Py/blob/master/examples/pyesprima.py) which supports the whole JS6 together with comments and much more. To parse comments just use:

    esprima.parse('//test', {'comment': True})

It is just like normal esprima but in python :) One downside - quite slow.
